version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker run --rm --name build -v /root/.m2:/root/.m2 -v "$CODEBUILD_SRC_DIR":/usr/magnum -w /usr/magnum 824214588663.dkr.ecr.ap-south-1.amazonaws.com/build/maven:3.8.1-jdk-11 mvn clean install -DskipTests
      - docker build -f Dockerfile -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:${CODEBUILD_BUILD_NUMBER} "$CODEBUILD_SRC_DIR"/
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:${CODEBUILD_BUILD_NUMBER}
cache:
  paths:
    - /root/.m2/**/*

